apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-niota-in-tls
spec:
  secretName: dev-niota-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dev.niota.in
  dnsNames:
    - dev.niota.in